class HwpIngestError(Exception): ...


class DocumentInfo:
    @property
    def page_count(self) -> int: ...


class ConvertReport:
    @property
    def output_path(self) -> str: ...
    @property
    def page_count(self) -> int: ...
    @property
    def pages_converted(self) -> int: ...
    @property
    def output_bytes(self) -> int: ...


def analyze_hwp_bytes(data: bytes) -> DocumentInfo: ...
def hwp_to_pdf_bytes(data: bytes, page_index: int | None = None) -> bytes: ...
def hwp_to_pdf_file(input_path: str, output_path: str, page_index: int | None = None) -> ConvertReport: ...
